{{- if not .Values.secrets.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurora.fullname" . }}-secrets-app
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.app }}
  {{- if ne $key "existingSecret" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
